# Generated by Django 2.2.6 on 2019-10-31 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stme', '0005_auto_20191031_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_p',
            field=models.ImageField(upload_to='post_img/'),
        ),
    ]
